### ISSUE TITLE
[Enhancement] Switch for native installer's installation directory

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/chocolatey#32]
This will be after 1.0. This is likely going to be a very involved process of getting intimate with the installation types themselves and install directories.

**Comment by voltagex** [comment]
Couldn't this also be done with directory junctions?

**Comment by Tim-Lei** [comment]
+1

**Comment by alexchandel** [comment]
A complementary option, which becomes more viable as chocolatey grows, and is ultimately optimal for chocolatey, is to persuade developers to provide `.zip`/`.7z` releases instead of `msi`/`exe`s. Archives can easily be made into self-contained chocolatey packages.

In most cases this requires little to no refactoring on their part. The primary difficulty lies in the set of packages that ship different, incompatible versions of MinGW, i.e. [StrawberryPerl](https://chocolatey.org/packages/StrawberryPerl), [HaskellPlatform](https://chocolatey.org/packages/HaskellPlatform), etc. These packages already fail unpredictably when they are merely present in the wrong order on the PATH. Eventually, each of these will need to either: harmonize around one version of MinGW, which chocolatey would provide as a package, shimmed in C:\ProgramData\chocolatey\bin\`; or be refactored to locate their compiler toolchain in their own sandbox (e.g. StrawberryPerl would find its linker at `$(dirname perl.exe)/../../c/bin/ld.exe` rather than the `ld.exe` in the PATH).

**Comment by psylver** [comment]
+1

**Comment by fracz** [comment]
+1

**Comment by theonlylawislove** [comment]
+1

**Comment by vinz243** [comment]
+1

**Comment by n8v** [comment]
+1

**Comment by z11k** [comment]
+1

**Comment by marazt** [comment]
+1

**Comment by jfcabral** [comment]
+1 I think this would be very useful, specially for people using SSDs!

**Comment by LukasMa** [comment]
+1 !

**Comment by ferventcoder** [comment]
This has been moved to https://github.com/chocolatey/choco/issues/258
