### ISSUE TITLE
shim exe with icon of the exe

### ISSUE THREAD

**Issue by ghiboz** [chocolatey/chocolatey#579]
hi!
it's possible in the exe created into `C:\ProgramData\chocolatey\bin` that points to the latest update to have the icon of the correct exe and not all the same?

thanks

**Comment by ferventcoder** [comment]
If you want to play with this, there is a prerelease https://chocolatey.org/packages/chocolatey/0.9.8.29-alpha1

**Comment by ferventcoder** [comment]
So it works if it finds the path. However the working directory of shimgen doesn't find it appropriately :/

**Comment by kbauer** [comment]
Regarding shims vs mklink: Back when I still used Windows XP I used Windows's *.LNK files as shims for programs I wanted to start from the commandline. 

The link contents just have to be 

    "EXECUTABLEPATH" %*

Instead of just `"EXECUTABLEPATH"`, with execution path set appropriately. Then you need to add `.LNK` to the `PATHEXT` variable. 

In order to allow calling the program as `COMMAND.exe`, adding a second link `COMMAND.exe.lnk` might do the trick.

One advantage of LNK files would be that it inherits the executable's icon. I am not aware of disadvantages. Sadly I'm *also* not aware of how to generate .LNK files.
