### ISSUE TITLE
[Enhancement] Download command

### ISSUE THREAD

**Issue by svnpenn** [chocolatey/chocolatey#614]
apt-get has these capabilities:

- `apt-get download`

 Download the binary package into the current directory

- `apt-get install --download-only`

 Download only - do NOT install or unpack archives

I feel that Chocolatey should have one of these as well. Something like

    choco download hello-world

That would download the appropriate file (zip or exe or iso) to either `%TEMP%\chocolatey` or the current directory.

**Comment by dragon788** [comment]
@svnpenn The challenge may be that Chocolatey actually downloads a nupkg from Chocolatey.org first, so are you wanting it to grab the package (.deb) or the actual installer from inside the package (exe pointed to by chocolateyInstall.ps1)? I believe that in the paid versions of Chocolatey they have added a function to just grab the nupkg for modification, and I'd wager you want the latter behavior of getting the installer itself, in this case I agree this would be somewhat handy if you were doing a setup where you wanted to cache all the packages to convert them to internally sourced installs instead of going outside of an enterprise network.

**Comment by ferventcoder** [comment]
Yup - https://chocolatey.org/docs/features-automatically-recompile-packages

**Comment by ferventcoder** [comment]
This is closed by https://github.com/chocolatey/choco/issues/108
